### ISSUE TITLE
can't use the package destine

### ISSUE THREAD

**Issue by benaaa** [InseeFr/Destinie-2#1]
I got this error when I'm trying to install the package destinie
devtools:: install_github("InseeFr/Destinie-2")
Erreur : HTTP error 404.
  No commit found for the ref master
  Did you spell the repo owner (`InseeFr`) and repo name (`Destinie-2`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by ACL90** [comment]
Can you try :

#If you are using Windows, please do first:
devtools :: find_rtools ()
#or pkgbuild:: find_rtools ()
#you should get a "TRUE"

#Then:
devtools :: install _github("InseeFr/Destinie-2",rep="release")

------
PS: I have not tested Destinie2 since long, but this is what we had suggested in the documentation.pdf, p106 (in French only) available here: https://github.com/InseeFr/Destinie-2/tree/release_ssparam/documentation

**Comment by benaaa** [comment]
Thank you but I did it and I got it "TRUE".
When i use the syntax devtools :: install _github("InseeFr/Destinie-2",rep="release")
I got : Error in devtools::install_github("InseeFr/Destinie-2", rep = "release") : 
  l'argument 2 correspond à plusieurs arguments formels
thats why I used the syntax devtools:: install_github("InseeFr/Destinie-2") and I got the error that i said above. Please could you help me I really need it for my university research

**Comment by ACL90** [comment]
Please try with:
devtools::install_github("InseeFr/Destinie-2",ref="release")

**Comment by benaaa** [comment]
IT WORKS!! Thank you so much

**Comment by benaaa** [comment]
IT WORKS!! Thank you so much

**Comment by benaaa** [comment]
IT WORKS!! Thank you so much
